// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHaJCSjS34qadz7_dBTo39g20sZYV2Vgg',
    appId: '1:110763433888:android:eb6c668ae3405db06d4ec5',
    messagingSenderId: '110763433888',
    projectId: 'flutter-bloc-firebase-example',
    storageBucket: 'flutter-bloc-firebase-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaEN1H-ltvlDnLOOuzNANrnPr87undJcs',
    appId: '1:110763433888:ios:2c9122895681b7096d4ec5',
    messagingSenderId: '110763433888',
    projectId: 'flutter-bloc-firebase-example',
    storageBucket: 'flutter-bloc-firebase-example.appspot.com',
    iosClientId: '110763433888-h4qhv11ncdh2sfirvesft1qiurrf9s0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocFirebaseExam',
  );
}
